module.exports=[64924,a=>{"use strict";a.s(["blobToBinaryString",0,function(a){return new Promise((b,c)=>{let d=new FileReader;d.onload=()=>{let a=new Uint8Array(d.result),c="";for(let b=0;b<a.length;b+=1)c+=String.fromCharCode(a[b]);b(c)},d.onerror=()=>c(Error("อ่านข้อมูล PDF ไม่สำเร็จ")),d.readAsArrayBuffer(a)})},"canvasBlob",0,function(a,b="image/jpeg",c=.92){return new Promise((d,e)=>{a.toBlob(a=>{a?d(a):e(Error("สร้างไฟล์ PDF ไม่สำเร็จ"))},b,c)})},"pdfBlobFromJpeg",0,function(a,b,c,d,e){let f=72/25.4*b,g=72/25.4*c,h=[],i=[0],j=0;function k(a){h.push(a),j+=a.length}function l(a,b){i[a]=j,k(`${a} 0 obj
${b}
endobj
`)}k("%PDF-1.4\n"),l(1,"<< /Type /Catalog /Pages 2 0 R >>"),l(2,"<< /Type /Pages /Kids [3 0 R] /Count 1 >>"),l(3,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${f.toFixed(2)} ${g.toFixed(2)}] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>`),i[4]=j,k(`4 0 obj
<< /Type /XObject /Subtype /Image /Width ${d} /Height ${e} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${a.length} >>
stream
`),k(a),k("\nendstream\nendobj\n");let m=`q
${f.toFixed(2)} 0 0 ${g.toFixed(2)} 0 0 cm
/Im0 Do
Q`;l(5,`<< /Length ${m.length} >>
stream
${m}
endstream`);let n=j;k("xref\n0 6\n0000000000 65535 f \n");for(let a=1;a<=5;a+=1)k(`${String(i[a]).padStart(10,"0")} 00000 n 
`);k(`trailer
<< /Size 6 /Root 1 0 R >>
startxref
${n}
%%EOF`);let o=new Uint8Array(j),p=0;for(let a of h)for(let b=0;b<a.length;b+=1)o[p]=255&a.charCodeAt(b),p+=1;return new Blob([o],{type:"application/pdf"})},"wrapCanvasText",0,function(a,b,c){let d=b.split(/\s+/).filter(Boolean),e=[],f="";for(let b of d){let d=f?`${f} ${b}`:b;if(a.measureText(d).width<=c){f=d;continue}f&&e.push(f),f=b}return f&&e.push(f),e.length?e:[b]}])},88590,a=>{"use strict";var b=a.i(73281),c=a.i(64924);async function d(a){let d=Math.max(92,76+12*a.items.length+16*!!a.note),e=document.createElement("canvas");e.width=Math.round(464),e.height=Math.round(8*d);let f=e.getContext("2d");if(!f)throw Error("เบราว์เซอร์ไม่รองรับการสร้าง PDF");let g=e.width-24,h=e.width/2,i=28;function j(a,b,c,d){f.font=`${d?.bold?"700":"400"} ${d?.size||24}px Arial, Tahoma, sans-serif`,f.fillStyle=d?.color||"#111827",f.textAlign=d?.align||"left",f.fillText(a,b,c)}function k(a){f.save(),f.strokeStyle="#9ca3af",f.setLineDash([5,5]),f.beginPath(),f.moveTo(24,a),f.lineTo(g,a),f.stroke(),f.restore()}for(let d of(f.fillStyle="#ffffff",f.fillRect(0,0,e.width,e.height),f.fillStyle="#111827",f.textBaseline="top",j(a.store?.name||"Menu Store",h,i,{align:"center",size:34,bold:!0}),i+=44,j(a.code,h,i,{align:"center",size:17,color:"#374151"}),i+=27,j((0,b.formatDateTime)(a.createdAt),h,i,{align:"center",size:17,color:"#374151"}),k(i+=36),i+=18,a.items)){let a=(0,c.wrapCanvasText)(f,d.name,250);for(let c of(j(a[0],24,i,{size:22,bold:!0}),j((0,b.formatBaht)(d.lineTotal),g,i,{align:"right",size:22,bold:!0}),i+=25,a.slice(1)))j(c,24,i,{size:22,bold:!0}),i+=25;j(`${d.code} \xb7 ${d.category}`,24,i,{size:16,color:"#4b5563"}),j(`${d.quantity} x ${(0,b.formatBaht)(d.unitPrice)}`,g,i,{align:"right",size:16,color:"#4b5563"}),i+=34}for(let[c,d]of(k(i+=4),i+=18,[["Subtotal",a.subtotal],["Discount",a.discount],["Tax",a.tax]]))j(c,24,i,{size:19}),j((0,b.formatBaht)(d),g,i,{align:"right",size:19,bold:!0}),i+=30;if(j("Total",24,i+=4,{size:30,bold:!0}),j((0,b.formatBaht)(a.total),g,i,{align:"right",size:30,bold:!0}),k(i+=38),i+=24,j(`รูปแบบการชำระ : ${b.paymentMethodLabels[a.paymentMethod]}`,h,i,{align:"center",size:18,color:"#374151"}),i+=28,a.note){for(let b of(0,c.wrapCanvasText)(f,`หมายเหตุบิล : ${a.note}`,g-24))j(b,h,i,{align:"center",size:17,color:"#374151"}),i+=23;i+=7}j("ขอบคุณที่ใช้บริการ",h,i,{align:"center",size:18,color:"#374151"});let l=Math.min(e.height,Math.max(Math.ceil(i+30),Math.round(544))),m=document.createElement("canvas");m.width=e.width,m.height=l;let n=m.getContext("2d");if(!n)throw Error("เบราว์เซอร์ไม่รองรับการสร้าง PDF");n.drawImage(e,0,0);let o=await (0,c.canvasBlob)(m),p=await (0,c.blobToBinaryString)(o);return{pdfBlob:(0,c.pdfBlobFromJpeg)(p,58,l/8,m.width,m.height),previewBlob:o}}async function e(a){return(await d(a)).pdfBlob}a.s(["createReceiptPdfBlob",0,e])}];

//# sourceMappingURL=frontend_src_components_receipt-desk-client_026vx9u._.js.map