var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/display/[displayId]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zbler.._.js")
R.c("server/chunks/ssr/0r9g_next_dist_0-x3.q8._.js")
R.c("server/chunks/ssr/0r9g_next_dist_esm_build_templates_app-page_0tnbc20.js")
R.c("server/chunks/ssr/[root-of-the-server]__0uk6~vl._.js")
R.c("server/chunks/ssr/0r9g_next_dist_11_ukvn._.js")
R.c("server/chunks/ssr/frontend_0t0o7fp._.js")
R.c("server/chunks/ssr/0r9g_next_dist_0z-qkv3._.js")
R.c("server/chunks/ssr/frontend_0uqtdv_._.js")
R.c("server/chunks/ssr/frontend_src_app_error_tsx_0kciie_._.js")
R.c("server/chunks/ssr/frontend_src_03qzjj5._.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_02pzh0k._.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_builtin_forbidden_0hywuao.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_builtin_unauthorized_059~5ae.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_builtin_global-error_06bh~5g.js")
R.c("server/chunks/ssr/frontend__next-internal_server_app_display_[displayId]_page_actions_12sjzme.js")
R.m(83025)
module.exports=R.m(83025).exports
