export const desktopFinePointerClass = "[@media(min-width:1181px)_and_(pointer:fine)]";

export const ipadMiniSaleProductCardClass =
  "[@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!min-h-[194px] [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!gap-[5px] [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!p-2.5 [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!pb-9";
export const ipadMiniSaleProductMediaClass = "[@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!block";
export const ipadMiniSaleProductImageClass =
  "[@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!h-16 [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!w-[calc(100%-54px)] [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!max-w-[118px] [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!rounded-[9px]";
export const ipadMiniSaleProductNameMiniClass =
  "[@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!grid [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!justify-items-start [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!text-left [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!mt-1.5";
export const ipadMiniSaleProductMetaClass =
  "[@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!mt-[3px] [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!justify-items-start [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!gap-px [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!text-left";
export const ipadMiniSaleProductPriceClass =
  "[@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!absolute [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!right-2.5 [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!top-2.5 [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!z-[1] [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!text-right [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!text-[0.92rem] [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!leading-[1.05]";
export const ipadMiniSaleProductStatusClass = "[@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!block [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!text-left [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!text-[0.68rem] [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!leading-[1.15]";
export const ipadMiniSaleProductDetailClass = "[@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!block [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!max-w-full [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!text-left [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!text-[0.58rem] [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!leading-[1.15]";
export const ipadMiniSaleProductCodeClass = "[@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!block [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!max-w-full [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!text-left [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!text-[0.56rem] [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!leading-[1.15] [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!tracking-[0.08em]";
export const ipadMiniSaleProductStockMiniClass = "[@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!block [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!mt-[3px] [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!max-w-[106px] [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!text-left [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!text-[0.62rem] [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!leading-[1.15]";
export const ipadMiniSaleProductHideClass = "[@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!hidden";
export const ipadMiniSaleProductButtonClass =
  "[@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!bottom-3.5 [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!left-auto [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!right-2.5 [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!h-12 [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!min-h-12 [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!w-12 [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!min-w-12 [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!gap-0 [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!rounded-[10px] [@media(min-width:821px)_and_(max-width:1024px)_and_(orientation:landscape)]:!p-0";

export const posWideShortSaleProductGridClass =
  "[@media(min-width:1181px)_and_(max-width:1280px)_and_(max-height:720px)_and_(orientation:landscape)_and_(pointer:fine)]:!grid-cols-2";
export const desktopHDSaleProductGridClass =
  "[@media(width:1600px)_and_(height:900px)_and_(orientation:landscape)]:!grid-cols-2";
export const posWideShortSaleProductCategoryClass =
  "[@media(min-width:1181px)_and_(max-width:1280px)_and_(max-height:720px)_and_(orientation:landscape)_and_(pointer:fine)]:!block [@media(min-width:1181px)_and_(max-width:1280px)_and_(max-height:720px)_and_(orientation:landscape)_and_(pointer:fine)]:!max-w-[150px] [@media(min-width:1181px)_and_(max-width:1280px)_and_(max-height:720px)_and_(orientation:landscape)_and_(pointer:fine)]:!overflow-visible [@media(min-width:1181px)_and_(max-width:1280px)_and_(max-height:720px)_and_(orientation:landscape)_and_(pointer:fine)]:!whitespace-nowrap";
export const androidTabletLandscapeSaleProductCategoryClass =
  "[@media(min-width:1181px)_and_(max-width:1280px)_and_(min-height:721px)_and_(max-height:800px)_and_(orientation:landscape)_and_(any-pointer:coarse)]:!block [@media(min-width:1181px)_and_(max-width:1280px)_and_(min-height:721px)_and_(max-height:800px)_and_(orientation:landscape)_and_(any-pointer:coarse)]:!max-w-[150px] [@media(min-width:1181px)_and_(max-width:1280px)_and_(min-height:721px)_and_(max-height:800px)_and_(orientation:landscape)_and_(any-pointer:coarse)]:!overflow-visible [@media(min-width:1181px)_and_(max-width:1280px)_and_(min-height:721px)_and_(max-height:800px)_and_(orientation:landscape)_and_(any-pointer:coarse)]:!whitespace-nowrap";
export const oldPosLowHeightSaleProductButtonClass =
  "[@media(width:1366px)_and_(height:720px)_and_(orientation:landscape)]:!h-[48px] [@media(width:1366px)_and_(height:720px)_and_(orientation:landscape)]:!w-[48px] [@media(width:1366px)_and_(height:720px)_and_(orientation:landscape)]:!min-w-[48px] [@media(width:1366px)_and_(height:720px)_and_(orientation:landscape)]:!gap-0 [@media(width:1366px)_and_(height:720px)_and_(orientation:landscape)]:!px-0";
export const oldPosLowHeightSaleProductHideClass =
  "[@media(width:1366px)_and_(height:720px)_and_(orientation:landscape)]:hidden";
