// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/[section]" | "/display/[displayId]" | "/login" | "/owner" | "/owner/[section]" | "/superadmin" | "/superadmin/[section]"
type AppRouteHandlerRoutes = "/api/auth/csrf" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/owner-logo" | "/api/auth/owner-payment-settings" | "/api/auth/owner-profile" | "/api/auth/owner-theme" | "/api/auth/password" | "/api/auth/setup-pin" | "/api/auth/verify-pin" | "/api/customer-displays" | "/api/customer-displays/[displayId]" | "/api/customer-displays/[displayId]/events" | "/api/customer-displays/[displayId]/revoke" | "/api/customer-displays/[displayId]/state" | "/api/customer-displays/[displayId]/store" | "/api/products" | "/api/products/[productId]" | "/api/reports/profit.pdf" | "/api/reports/sales" | "/api/sales" | "/api/sales/[saleId]" | "/api/sales/[saleId]/receipt.pdf" | "/api/uploads/sign"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/[section]": { "section": string; }
  "/api/auth/csrf": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/owner-logo": {}
  "/api/auth/owner-payment-settings": {}
  "/api/auth/owner-profile": {}
  "/api/auth/owner-theme": {}
  "/api/auth/password": {}
  "/api/auth/setup-pin": {}
  "/api/auth/verify-pin": {}
  "/api/customer-displays": {}
  "/api/customer-displays/[displayId]": { "displayId": string; }
  "/api/customer-displays/[displayId]/events": { "displayId": string; }
  "/api/customer-displays/[displayId]/revoke": { "displayId": string; }
  "/api/customer-displays/[displayId]/state": { "displayId": string; }
  "/api/customer-displays/[displayId]/store": { "displayId": string; }
  "/api/products": {}
  "/api/products/[productId]": { "productId": string; }
  "/api/reports/profit.pdf": {}
  "/api/reports/sales": {}
  "/api/sales": {}
  "/api/sales/[saleId]": { "saleId": string; }
  "/api/sales/[saleId]/receipt.pdf": { "saleId": string; }
  "/api/uploads/sign": {}
  "/display/[displayId]": { "displayId": string; }
  "/login": {}
  "/owner": {}
  "/owner/[section]": { "section": string; }
  "/superadmin": {}
  "/superadmin/[section]": { "section": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
