// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/[section]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/[section]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/[section]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/display/[displayId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/display/[displayId]">> = Specific
  const handler = {} as typeof import("../../src/app/display/[displayId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/[section]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner/[section]">> = Specific
  const handler = {} as typeof import("../../src/app/owner/[section]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner">> = Specific
  const handler = {} as typeof import("../../src/app/owner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/superadmin/[section]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/superadmin/[section]">> = Specific
  const handler = {} as typeof import("../../src/app/superadmin/[section]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/superadmin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/superadmin">> = Specific
  const handler = {} as typeof import("../../src/app/superadmin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/csrf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/csrf">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/csrf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/owner-logo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/owner-logo">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/owner-logo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/owner-payment-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/owner-payment-settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/owner-payment-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/owner-profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/owner-profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/owner-profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/owner-theme/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/owner-theme">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/owner-theme/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/setup-pin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/setup-pin">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/setup-pin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/verify-pin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-pin">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/verify-pin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer-displays/[displayId]/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer-displays/[displayId]/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer-displays/[displayId]/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer-displays/[displayId]/revoke/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer-displays/[displayId]/revoke">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer-displays/[displayId]/revoke/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer-displays/[displayId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer-displays/[displayId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer-displays/[displayId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer-displays/[displayId]/state/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer-displays/[displayId]/state">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer-displays/[displayId]/state/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer-displays/[displayId]/store/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer-displays/[displayId]/store">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer-displays/[displayId]/store/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer-displays/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer-displays">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer-displays/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/products/[productId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[productId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/products/[productId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products">> = Specific
  const handler = {} as typeof import("../../src/app/api/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/profit.pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/profit.pdf">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/profit.pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/sales/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/sales">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/sales/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sales/[saleId]/receipt.pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales/[saleId]/receipt.pdf">> = Specific
  const handler = {} as typeof import("../../src/app/api/sales/[saleId]/receipt.pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sales/[saleId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales/[saleId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/sales/[saleId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sales/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales">> = Specific
  const handler = {} as typeof import("../../src/app/api/sales/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/uploads/sign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uploads/sign">> = Specific
  const handler = {} as typeof import("../../src/app/api/uploads/sign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
